Add aggregation parsing to Elasticsearch Filebeat producer
thought-machine/dracon pull request #86
Opened 2021-01-08 13:02 UTC by markchalloner

2021-01-08 14:55 UTC, chrisnovakovic requested changes
Looks good 🙂 Just a couple of nits...

2021-01-08 14:55 UTC, chrisnovakovic commented on producers/elasticsearch_filebeat/types/elasticsearch-filebeat-issue.go
> +	Aggregations ElasticSearchFilebeatAggregations `json:"aggregations"`
nit: no column alignment

```
Hits         ElasticSearchFilebeatHits         `json:"hits"`
Aggregations ElasticSearchFilebeatAggregations `json:"aggregations"`
```

2021-01-08 14:55 UTC, chrisnovakovic commented on producers/elasticsearch_filebeat/types/elasticsearch-filebeat-issue.go
> +	Name    string 					   `json:"key"`
nit: incorrect column alignment

2021-01-08 15:10 UTC, markchalloner commented
Fixed some whitespace issues in the test data. Diff without whitespace:

https://github.com/thought-machine/dracon/pull/86/files?w=1

2021-01-08 15:37 UTC, chrisnovakovic requested changes

2021-01-08 15:37 UTC, chrisnovakovic commented on producers/elasticsearch_filebeat/types/elasticsearch-filebeat-issue.go
> +    Name    string                     `json:"key"`
nit: still off by one here (between the field name and the type)

2021-01-11 10:16 UTC, chrisnovakovic requested changes
One remaining nit...

2021-01-11 12:08 UTC, markchalloner commented
ah sorry good eye, thought I had resolved all these, fixing

2021-01-11 13:07 UTC, chrisnovakovic approved these changes

2021-01-11 13:07 UTC, merged